jwt:
  secret: UIAM_$#*%19Q%J3d"c-4;tk7}tWo7iEV:o^B1av?!|C&^V,-tfp+!nOCm-<]1A(JzQIaDD"c-4;tk7}tWo7iEV:o^B1av?!|C&^V,-_DFL*YSBGB)BpnoQ3`!ZxRK1s
spring:
  application:
    name: goppho
  datasource:
    url: jdbc:postgresql://localhost:5432/goppho_database
    username: goppho_database_admin
    password: anganamma
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true