jwt:
  secret: wVf82Q4g9jU1aK7xL0wVf82Q4wVf82Q4g9jU1aK7xL0oZ3bYc6eRtIuP/mHnJ+sWvA1k=g9jU1aK7xL0oZ3bYc6eRtIuP/mHnJ+sWvA1k=oZ3bYc6eRtIuP/mHnJ+sWvA1k=
  exp: 3600000
spring:
  application:
    name: goppho
  datasource:
    url: jdbc:postgresql://localhost:5432/goppho_database
    username: goppho_database_admin
    password: anganamma
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 465
    username: noreplytgc23@gmail.com
    password: oyhppqbiqihnkpxc
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true