jwt:
  secret: wVf82Q4g9jU1aK7xL0wVf82Q4wVf82Q4g9jU1aK7xL0oZ3bYc6eRtIuP/mHnJ+sWvA1k=g9jU1aK7xL0oZ3bYc6eRtIuP/mHnJ+sWvA1k=oZ3bYc6eRtIuP/mHnJ+sWvA1k=
  exp: 3600000
spring:
  application:
    name: goppho
  datasource:
    url: jdbc:postgresql://localhost:5432/goppho_database
    username: goppho_database_admin
    password: anganamma
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true